# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: hakhverd@ualberta.ca
    url: hakhverd@ualberta.ca
    weight: 10
#   - name: Topics
#     url: tags/
#     weight: 20
#   - name: Uses
#     url: uses/
#     weight: 30
