# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: /#pubs
    weight: 20
  - name: Experience
    url: /#exp
    weight: 30
  - name: Blog
    url: /#blog
    weight: 40
  
